export enum MenuActionTypes {
  HOME = "SWITCH-HOME",
  SEARCH = "SWITCH-SEARCH",
  ALBUM = "SWITCH-ALBUM",
  PLAYLIST = "SWITCH-PLAYLIST",
  ARTIST = "SWITCH-ARTIST",
  LIST = "SWITCH-LIST",
  LYRICS = "SWITCH-LYRICS",

  PREVIOUS = "SWITCH-TO-PREVIOUS",
  NEXT = "SWITCH-TO-NEXT",
  
  SET_CURRENT_COLOR = "SET-CURRENT-COLOR",
}
